[GenelAyarlar]
ForceStop=0
AdminMessage=Sistem aktif.

[Lisanslar]
178BFBFF00A50F00=20300101

[Moduller]
; 'GenelMakro' kısmını kaldırdım çünkü MainLoader kendini güncelleyemez.
; Sadece alt makroları buraya ekleyin.

; Linkin içinde %20 veya Türkçe karakter olmamasına dikkat edin.
OtomatikOturum=1.0|2|https://raw.githubusercontent.com/gamebizstore-cloud/LegalFlow/main/SoftwareDepot/OturumBaglantisi/OturumBaglantisi.ahk