[GenelAyarlar]
ForceStop=0
AdminMessage=Sistem aktif.

[Lisanslar]
; Buraya kendi bilgisayarının HWID numarasını yazmalısın.
; Programın verdiği hatadaki ID'yi buraya yapıştır.
178BFBFF00A50F00=20300101

[Moduller]

GenelMakro=1.0|2|https://raw.githubusercontent.com/gamebizstore-cloud/LegalFlow/refs/heads/main/Source/MainLoader.ahk
OtomatikOturumBağlantısı=1.0|1|https://raw.githubusercontent.com/gamebizstore-cloud/LegalFlow/refs/heads/main/Software%20Depot/Oturum%20Bağlantısı/Oturum%20Bağlantısı.ahk

