[GenelAyarlar]
ForceStop=0
AdminMessage=Sistem aktif.

[Lisanslar]
; Buraya kendi bilgisayarının HWID numarasını yazmalısın.
; Programın verdiği hatadaki ID'yi buraya yapıştır.
SENIN_HWID_NUMARAN=20300101

[Moduller]
GenelMakro=1.2|1|https://raw.githubusercontent.com/gamebizstore-cloud/LegalFlow/refs/heads/main/Source/MainLoader.ahk